version: 0.2

env:
  variables:
    CWQA_ADDITIONALPYTESTARGS: ''
    CWQA_TARGETENV: ''
    
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # install poetry
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=/root/.local/bin:$PATH
      - poetry install
  build:
    commands:
      - |
        if [[ "${CWQA_ADDITIONALPYTESTARGS}" != "" ]]; then
          CWQA_ADDITIONALPYTESTARGS="--pytest-args \"${CWQA_ADDITIONALPYTESTARGS}\""
        else
          CWQA_ADDITIONALPYTESTARGS=''
        fi
        echo "${CWQA_ADDITIONALPYTESTARGS}"
        if [[ "${CWQA_TARGETENV}" != "" ]]; then
          export CWQA_TARGETENV="--target-env \"${CWQA_TARGETENV}\""
        else
          export CWQA_TARGETENV=''
        fi
        echo "${CWQA_TARGETENV}"
      - >
        echo poetry run execute-pytest
        --config ${CWQA_EXECUTIONCONFIGURATION} ${CWQA_ADDITIONALPYTESTARGS} ${CWQA_TARGETENV}
      - >
        poetry run execute-pytest
        --config ${CWQA_EXECUTIONCONFIGURATION} ${CWQA_ADDITIONALPYTESTARGS} ${CWQA_TARGETENV}
artifacts:
  files:
    - 'execution_report.json'
    - 'execution_report.xml'
reports:
  execution-reports:
    files:
      - "execution_report.xml"
    file-format: "JUNITXML"
