version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # install poetry
      - curl -sSL https://install.python-poetry.org | python3 -
      - poetry install
  build:
    commands:
      - poetry run execute-pytest --config All_Tests_X
artifacts:
  files:
    - '**/*'
