version: 0.2

env:
  variables:
    CWQA_ADDITIONALPYTESTARGS: 'hello world'
    CWQA_TARGETENV: ''
    
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # install poetry
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=/root/.local/bin:$PATH
      - poetry install
  build:
    commands:
      - |
        if expr "${CWQA_ADDITIONALPYTESTARGS}" : "" >/dev/null; then
          echo 'Non-Empty pytest args'
          echo '${CWQA_ADDITIONALPYTESTARGS}'
        else
          echo 'Empty pytest args'
        fi
      #- export EMPTY_STRING=''
      #- export PYTEST_ARGS='--pytest-arg ${CWQA_ADDITIONALPYTESTARGS}' if '${CWQA_ADDITIONALPYTESTARGS}' != '' else ''
      #- echo 'PYTEST_ARGS:' + $PYTEST_ARGS
      #- >
      #  poetry run execute-pytest
      #  --config ${CWQA_EXECUTIONCONFIGURATION} $PYTEST_ARGS
artifacts:
  files:
    - 'execution_report.json'
    - 'execution_report.xml'
reports:
  execution-reports:
    files:
      - "execution_report.xml"
    file-format: "JUNITXML"
