version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # install poetry
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=/root/.local/bin:$PATH
      - poetry install
  build:
    commands:
      - >
        poetry run execute-pytest
        --config ${CWQA_EXECUTIONCONFIGURATION}
        --pytest-args ${CWQA_ADDITIONALPYTESTARGS:#('')}
        --target-env ${CWQA_TARGETENV:#('')}
artifacts:
  files:
    - 'execution_report.json'
    - 'execution_report.xml'
reports:
  execution-reports:
    files:
      - "execution_report.xml"
    file-format: "JUNITXML"
